
title: Brenden Connors
email: connors123123@yahoo.com
description: >- # this means to ignore newlines until "baseurl:"
  Personal website of Brenden Connors. This website will showcase various data science
  topics including machine learning projects, data visualizations, and tutorials.
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://brenden-connors.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  brendenconnors


# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  data_visualizations:
    output: true
  machine_learning_projects:
    output: true
  tutorials:
    output: true
    

